### ISSUE TITLE
di:compile Issues

### ISSUE THREAD

**Issue by jksimoniii** [shipperhq/module-common#3]
Running setup:di:compile throws the following _errors_ although the compilation never actually fails.  I haven't been able to identify a fix yet, but will report back if I find something.

```
ShipperHQ\Common\Helper\Data
    Incorrect dependency in class ShipperHQ\Common\Helper\Data in app/code/ShipperHQ/Common/Helper/Data.php \Magento\Framework\Module\Manager already exists in context object
```

**Comment by birchestx** [comment]
thanks, will investigate today.  We had this working a couple of weeks ago as I tested it, will see whats going on.

**Comment by wsagen** [comment]
Closing as now resolved
