### ISSUE TITLE
20.3.7 - ShipperHQ\Lib\AdminOrder\AbstractService does not exist

### ISSUE THREAD

**Issue by Silarn** [shipperhq/module-common#4]
The class added in this latest release tries to use another class:

use ShipperHQ\Lib\AdminOrder\AbstractService;

This class does not exist and will cause errors during compilation.

**Comment by wsajason** [comment]
From your description you pulled code during an update to the repos. If you update library-shipper that will resolve.

**Comment by Silarn** [comment]
In that case you should probably key the new version to the updated library requirement so that it doesn't do a bad update on an outdated dependency.

**Comment by Silarn** [comment]
Actually, I'm still seeing the compilation error even with the updated library-shipper. But let me try flushing cache.

**Comment by Silarn** [comment]
No, and if I look at the code for the new release, there is no AdminOrder\AbstractService in the new code.

**Comment by wsajason** [comment]
That's been corrected on library-shipper. Tag 20.5.1.

**Comment by Silarn** [comment]
Okay, thanks.
